import {
  collection,
  getDocs,
  query,
  where,
  orderBy,
  deleteDoc,
  doc,
  getDoc,
  setDoc,
  arrayUnion,
  serverTimestamp,
  onSnapshot
} from 'firebase/firestore';
import { db } from './firebaseConfig';
import { NoteModel, VideoQnAModel, normalizeVideoMetadata } from '../../models';
import { extractYouTubeVideoId } from '../../utils/router';

export { extractYouTubeVideoId as extractYoutubeVideoId };

/**
 * Saves a completed note generation task into Firestore.
 * Uses a deterministic doc ID `${userId}_${videoId}` to guarantee no duplicate records.
 * @param {string} userId - Auth user ID
 * @param {string} videoUrl - YouTube video URL
 * @param {Object} metadata - Extracted video metadata (title, author, duration, thumbnail, language, etc.)
 * @param {Object} result - Generated notes and outline result
 * @returns {Promise<string>} Created document ID
 */
export async function saveNotes(userId, videoUrl, metadata, result) {
  if (!userId) throw new Error('User must be logged in to save notes.');

  const norm = normalizeVideoMetadata({ videoUrl, metadata, ...metadata });
  const cleanVideoId = norm?.videoId || extractYouTubeVideoId(videoUrl, { allowPlainId: true });
  if (!cleanVideoId) {
    throw new Error('Valid video ID is required to save notes.');
  }

  const docId = `${userId}_${cleanVideoId}`;
  const docRef = doc(db, 'notes', docId);

  const model = new NoteModel({
    id: docId,
    userId,
    videoId: cleanVideoId,
    videoUrl: norm?.videoUrl || videoUrl || `https://www.youtube.com/watch?v=${cleanVideoId}`,
    metadata: norm?.metadata || metadata,
    result,
  });

  await setDoc(docRef, model.toFirestore({ isNew: true }), { merge: true });

  return docId;
}

/**
 * Retrieves all notes generated by a specific user with automatic deduplication by videoId.
 * @param {string} userId - Auth user ID
 * @returns {Promise<Array<NoteModel>>} Array of unique NoteModel instances
 */
export async function getUserNotes(userId) {
  if (!userId) return [];

  const notesRef = collection(db, 'notes');
  try {
    let querySnapshot;
    try {
      const q = query(
        notesRef,
        where('userId', '==', userId),
        orderBy('createdAt', 'desc')
      );
      querySnapshot = await getDocs(q);
    } catch (indexErr) {
      console.warn('Composite index may be missing for notes query, falling back to in-memory sorting:', indexErr);
      const fallbackQ = query(notesRef, where('userId', '==', userId));
      querySnapshot = await getDocs(fallbackQ);
    }

    const notes = [];
    const seenVideoIds = new Set();

    querySnapshot.forEach((docSnap) => {
      const note = NoteModel.fromFirestore(docSnap);
      if (note && note.videoId && !seenVideoIds.has(note.videoId)) {
        seenVideoIds.add(note.videoId);
        notes.push(note);
      }
    });

    notes.sort((a, b) => {
      const timeA = a.createdAtDate ? a.createdAtDate.getTime() : 0;
      const timeB = b.createdAtDate ? b.createdAtDate.getTime() : 0;
      return timeB - timeA;
    });

    return notes;
  } catch (err) {
    console.error('Error fetching user notes archive:', err);
    return [];
  }
}

/**
 * Subscribes to real-time updates of all notes generated by a specific user with deduplication.
 * @param {string} userId - Auth user ID
 * @param {Function} onUpdate - Callback receiving array of unique NoteModel instances
 * @returns {Function} Unsubscribe function
 */
export function subscribeUserNotes(userId, onUpdate) {
  if (!userId) return () => {};

  const notesRef = collection(db, 'notes');
  const q = query(
    notesRef,
    where('userId', '==', userId)
  );

  return onSnapshot(
    q,
    (querySnapshot) => {
      const notes = [];
      const seenVideoIds = new Set();

      querySnapshot.forEach((docSnap) => {
        const note = NoteModel.fromFirestore(docSnap);
        if (note && note.videoId && !seenVideoIds.has(note.videoId)) {
          seenVideoIds.add(note.videoId);
          notes.push(note);
        }
      });

      notes.sort((a, b) => {
        const timeA = a.createdAtDate ? a.createdAtDate.getTime() : 0;
        const timeB = b.createdAtDate ? b.createdAtDate.getTime() : 0;
        return timeB - timeA;
      });

      onUpdate(notes);
    },
    (err) => {
      console.error('Error in real-time user notes subscription:', err);
    }
  );
}

/**
 * Deletes a saved note document if it belongs to the authenticated user.
 * @param {string} userId - Auth user ID (UID)
 * @param {string} noteId - Firestore document ID
 * @returns {Promise<void>}
 */
export async function deleteNotes(userId, noteId) {
  if (!userId || !noteId) return;
  const docRef = doc(db, 'notes', noteId);
  const docSnap = await getDoc(docRef);
  if (docSnap.exists()) {
    const note = NoteModel.fromFirestore(docSnap);
    if (note?.userId !== userId) {
      throw new Error('Unauthorized: You do not have permission to delete this note.');
    }
    await deleteDoc(docRef);
    return;
  }

  // Also attempt deleting deterministic document if noteId was bare videoId
  const directRef = doc(db, 'notes', `${userId}_${noteId}`);
  const directSnap = await getDoc(directRef);
  if (directSnap.exists()) {
    await deleteDoc(directRef);
  }
}

/**
 * Retrieves a single note document belonging to the user matching a YouTube video ID.
 * Performs fast O(1) lookup on deterministic ID, with graceful fallback for legacy docs.
 * @param {string} userId - Auth user ID
 * @param {string} videoId - YouTube video ID
 * @returns {Promise<NoteModel|null>} The note model or null
 */
export async function getNoteByVideoId(userId, videoId) {
  if (!userId || !videoId) return null;
  const cleanVideoId = extractYouTubeVideoId(videoId, { allowPlainId: true }) || String(videoId).trim();
  if (!cleanVideoId) return null;

  // 1. Direct O(1) primary lookup by deterministic ID `${userId}_${cleanVideoId}`
  try {
    const docRef = doc(db, 'notes', `${userId}_${cleanVideoId}`);
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      return NoteModel.fromFirestore(docSnap);
    }
  } catch (directErr) {
    console.warn('Direct deterministic note lookup error:', directErr);
  }

  // 2. Fallback query for legacy auto-generated document IDs
  try {
    const notesRef = collection(db, 'notes');
    const q = query(
      notesRef,
      where('userId', '==', userId)
    );

    const querySnapshot = await getDocs(q);
    let foundNote = null;

    querySnapshot.forEach((docSnap) => {
      if (foundNote) return;
      const note = NoteModel.fromFirestore(docSnap);
      if (note) {
        if (note.videoId === cleanVideoId) {
          foundNote = note;
          return;
        }
        const parsedId = extractYouTubeVideoId(note.videoUrl, { allowPlainId: true });
        if (parsedId === cleanVideoId) {
          foundNote = note;
        }
      }
    });

    return foundNote;
  } catch (err) {
    console.error('Error in fallback getNoteByVideoId:', err);
    return null;
  }
}

/**
 * Retrieves a single note document by its Firestore document ID.
 * @param {string} noteId - Firestore document ID
 * @returns {Promise<NoteModel|null>} The note model or null
 */
export async function getNoteById(noteId) {
  if (!noteId) return null;
  const docRef = doc(db, 'notes', noteId);
  const docSnap = await getDoc(docRef);

  return NoteModel.fromFirestore(docSnap);
}

/**
 * Appends new video QnA chat messages to the conversation history for a specific user and video.
 * @param {string} userId - Auth user ID
 * @param {string} videoId - YouTube video ID
 * @param {Array} messages - List of new chat messages to append
 */
export async function saveVideoQnAChat(userId, videoId, messages) {
  if (!userId || !videoId || !messages?.length) return;

  const model = new VideoQnAModel({
    userId,
    videoId,
    messages,
  });

  const docRef = doc(db, 'video_qnas', `${userId}_${videoId}`);
  await setDoc(docRef, {
    userId: model.userId,
    videoId: model.videoId,
    messages: arrayUnion(...model.messages),
    updatedAt: serverTimestamp(),
  }, { merge: true });
}

/**
 * Retrieves the video QnA chat history for a specific user and video.
 * @param {string} userId - Auth user ID
 * @param {string} videoId - YouTube video ID
 * @returns {Promise<Array>} List of chat messages
 */
export async function getVideoQnAChat(userId, videoId) {
  if (!userId || !videoId) return [];
  const docRef = doc(db, 'video_qnas', `${userId}_${videoId}`);
  const docSnap = await getDoc(docRef);
  if (docSnap.exists()) {
    const model = VideoQnAModel.fromFirestore(docSnap);
    return model?.messages || [];
  }
  return [];
}

/**
 * Deletes the video QnA chat history for a specific user and video.
 * @param {string} userId - Auth user ID
 * @param {string} videoId - YouTube video ID
 */
export async function deleteVideoQnAChat(userId, videoId) {
  if (!userId || !videoId) return;
  const docRef = doc(db, 'video_qnas', `${userId}_${videoId}`);
  await deleteDoc(docRef);
}
