import {
  collection,
  addDoc,
  getDocs,
  query,
  where,
  orderBy,
  deleteDoc,
  doc,
  getDoc,
  setDoc,
  serverTimestamp
} from 'firebase/firestore';
import { db } from './firebaseConfig';

/**
 * Saves a completed note generation task into Firestore.
 * @param {string} userId - Auth user ID
 * @param {string} videoUrl - YouTube video URL
 * @param {Object} metadata - Extracted video metadata (title, author, duration, thumbnail, language, etc.)
 * @param {Object} result - Generated notes and outline result
 * @returns {Promise<string>} Created document ID
 */
export async function saveNotes(userId, videoUrl, metadata, result) {
  if (!userId) throw new Error('User must be logged in to save notes.');

  const notesRef = collection(db, 'notes');
  const docRef = await addDoc(notesRef, {
    userId,
    videoUrl,
    metadata: metadata || {},
    result: result || {},
    createdAt: serverTimestamp()
  });

  return docRef.id;
}

/**
 * Retrieves all notes generated by a specific user.
 * @param {string} userId - Auth user ID
 * @returns {Promise<Array>} Array of notes documents with document ID
 */
export async function getUserNotes(userId) {
  if (!userId) return [];

  const notesRef = collection(db, 'notes');
  const q = query(
    notesRef,
    where('userId', '==', userId),
    orderBy('createdAt', 'desc')
  );

  const querySnapshot = await getDocs(q);
  const notes = [];

  querySnapshot.forEach((docSnap) => {
    const data = docSnap.data();
    // Convert Firestore Timestamp to JS Date if available
    const createdAtDate = data.createdAt ? data.createdAt.toDate() : new Date();

    notes.push({
      id: docSnap.id,
      ...data,
      createdAtDate
    });
  });

  return notes;
}

/**
 * Deletes a saved note document.
 * @param {string} noteId - Firestore document ID
 * @returns {Promise<void>}
 */
export async function deleteNotes(noteId) {
  if (!noteId) return;
  const docRef = doc(db, 'notes', noteId);
  await deleteDoc(docRef);
}

/**
 * Saves or updates user API keys in Firestore.
 * @param {string} userId - Auth user ID (UID)
 * @param {string} googleApiKey - Gemini API Key
 */
export async function saveUserApiKeys(userId, googleApiKey) {
  if (!userId) throw new Error('User must be logged in to save API keys.');

  const docRef = doc(db, 'user_api_keys', userId);
  await setDoc(docRef, {
    googleApiKey: googleApiKey || '',
    updatedAt: serverTimestamp()
  }, { merge: true });
}

/**
 * Retrieves the user's API keys from Firestore.
 * @param {string} userId - Auth user ID (UID)
 * @returns {Promise<{googleApiKey: string}>} The API keys object
 */
export async function getUserApiKeys(userId) {
  if (!userId) return { googleApiKey: '' };

  const docRef = doc(db, 'user_api_keys', userId);
  const docSnap = await getDoc(docRef);

  if (docSnap.exists()) {
    const data = docSnap.data();
    return {
      googleApiKey: data.googleApiKey || ''
    };
  }

  return { googleApiKey: '' };
}

/**
 * Extracts the 11-character YouTube video ID from a URL.
 * @param {string} url - YouTube URL
 * @returns {string} YouTube video ID or empty string
 */
export function extractYoutubeVideoId(url) {
  if (!url) return '';
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
  const match = url.match(regExp);
  return (match && match[2].length === 11) ? match[2] : '';
}

/**
 * Retrieves a single note document belonging to the user matching a YouTube video ID.
 * @param {string} userId - Auth user ID
 * @param {string} videoId - YouTube video ID
 * @returns {Promise<Object|null>} The note document or null
 */
export async function getNoteByVideoId(userId, videoId) {
  if (!userId || !videoId) return null;
  const notesRef = collection(db, 'notes');
  const q = query(
    notesRef,
    where('userId', '==', userId)
  );

  const querySnapshot = await getDocs(q);
  let foundNote = null;

  querySnapshot.forEach((docSnap) => {
    const data = docSnap.data();
    const parsedId = extractYoutubeVideoId(data.videoUrl);
    if (parsedId === videoId) {
      const createdAtDate = data.createdAt ? data.createdAt.toDate() : new Date();
      foundNote = {
        id: docSnap.id,
        ...data,
        createdAtDate
      };
    }
  });

  return foundNote;
}
